server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerceapp_microservice
    username: root
    password: deep1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
